# 下面这些内容是为了让 MyBatis 映射
# 指定 Mybatis 的 Mapper 文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.tianshu.mybatis.entity


# 应用服务 WEB 访问端口
server:
  port: 51385


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.54.61/tianshu?characterEncoding=utf-8&useSSL=false&requireSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wl001017
    hikari:
      maximum-pool-size: 10  # 连接池最大连接数，根据实际情况调整
      connection-timeout: 30000  # 连接超时时间，30秒
      idle-timeout: 600000  # 空闲连接超时时间，10分钟
      max-lifetime: 1800000  # 连接池中的连接最大生存时间，30分钟
      validation-timeout: 5000  # 连接验证超时时间，5秒
      connection-test-query: SELECT 1  # 用于验证连接是否有效
#  jpa:
#    hibernate:
#      ddl-auto: update # 或者根据需要使用 `create`, `create-drop`, `validate`
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQLDialect
#          format_sql: true
#    show-sql: true
  redis:
    host: 101.35.54.61
    port: 6379
#    password: yourpassword  # 替换为你设置的密码
#    jedis:
#      pool:
#        max-idle: 10
#        min-idle: 2
#        max-active: 20
#        max-wait: 10000

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest


